name: Update IPTV Playlist with Progress

on:
  schedule:
    - cron: '0 4 * * *'  # tous les jours à 4h UTC
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # workflow plus long possible pour validation massive

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: List repo structure
        run: ls -R

      - name: Run validation script with progress
        run: |
          echo "Starting IPTV validation..."
          python generator/validate_streams_parallel_final.py | tee validation_log.txt

      - name: Display progress summary
        run: |
          echo "==== Progress Summary ===="
          grep "Progress:" validation_log.txt || echo "No progress logs found"
          echo "==== Channels Found ===="
          grep "flux" validation_log.txt || echo "No valid channels found"

      - name: Copy playlist to root
        run: |
          cp playlist/playlist_filtered.m3u playlist.m3u

      - name: Commit and push
        env:
          PAT_FLUX_TOKEN: ${{ secrets.PAT_FLUX_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add playlist/playlist_filtered.m3u playlist.m3u || echo "No changes"
          git commit -m "Automated playlist update" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${PAT_FLUX_TOKEN}@github.com/6erny6urns/iptv-fr-en-flux-capacitor.git
          git push origin main
