name: Validate M3U Playlists

on:
  workflow_dispatch:  # lancement manuel
  schedule:
    - cron: "0 6 * * *"  # chaque jour à 6h UTC

jobs:
  validate-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests tqdm

      - name: Run parse_filter_validate_m3u.py
        run: |
          python parse_filter_validate_m3u.py

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add results/*
          git commit -m "Mise à jour automatique des résultats M3U"
          git push
